package fr.formation.inti.entities;
// Generated 4 mai 2022, 11:33:36 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bookmaker generated by hbm2java
 */
@Entity
@Table(name = "bookmaker", catalog = "ligue1_gamble")
public class Bookmaker implements java.io.Serializable {

	private Integer bookmakerId;
	private Match match;
	private Integer betBalance;
	private Integer betProfit;

	public Bookmaker() {
	}

	public Bookmaker(Match match, Integer betBalance, Integer betProfit) {
		this.match = match;
		this.betBalance = betBalance;
		this.betProfit = betProfit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bookmaker_id", unique = true, nullable = false)
	public Integer getBookmakerId() {
		return this.bookmakerId;
	}

	public void setBookmakerId(Integer bookmakerId) {
		this.bookmakerId = bookmakerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "match_id")
	public Match getMatch() {
		return this.match;
	}

	public void setMatch(Match match) {
		this.match = match;
	}

	@Column(name = "bet_balance")
	public Integer getBetBalance() {
		return this.betBalance;
	}

	public void setBetBalance(Integer betBalance) {
		this.betBalance = betBalance;
	}

	@Column(name = "bet_profit")
	public Integer getBetProfit() {
		return this.betProfit;
	}

	public void setBetProfit(Integer betProfit) {
		this.betProfit = betProfit;
	}

}
