package fr.formation.inti.entities;
// Generated 4 mai 2022, 11:33:36 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Gambling generated by hbm2java
 */
@Entity
@Table(name = "gambling", catalog = "ligue1_gamble")
public class Gambling implements java.io.Serializable {

	private Integer gamblingId;
	private Bet bet;
	private User user;
	private Integer amount;
	private Date gamblingDate;
	private Float gain;

	public Gambling() {
	}

	public Gambling(Bet bet, User user, Integer amount, Date gamblingDate, Float gain) {
		this.bet = bet;
		this.user = user;
		this.amount = amount;
		this.gamblingDate = gamblingDate;
		this.gain = gain;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "gambling_id", unique = true, nullable = false)
	public Integer getGamblingId() {
		return this.gamblingId;
	}

	public void setGamblingId(Integer gamblingId) {
		this.gamblingId = gamblingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bet_id")
	public Bet getBet() {
		return this.bet;
	}

	public void setBet(Bet bet) {
		this.bet = bet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "amount")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "gambling_date", length = 10)
	public Date getGamblingDate() {
		return this.gamblingDate;
	}

	public void setGamblingDate(Date gamblingDate) {
		this.gamblingDate = gamblingDate;
	}

	@Column(name = "gain", precision = 12, scale = 0)
	public Float getGain() {
		return this.gain;
	}

	public void setGain(Float gain) {
		this.gain = gain;
	}

}
