package fr.formation.inti.entities;
// Generated 4 mai 2022, 11:33:36 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Match generated by hbm2java
 */
@Entity
@Table(name = "match", catalog = "ligue1_gamble")
public class Match implements java.io.Serializable {

	private Integer matchId;
	private Club clubByClubVisitor;
	private Club clubByClubHome;
	private Date date;
	private String location;
	private Set<Bet> bets = new HashSet<Bet>(0);
	private Set<Results> resultses = new HashSet<Results>(0);
	private Set<Bookmaker> bookmakers = new HashSet<Bookmaker>(0);

	public Match() {
	}

	public Match(Club clubByClubVisitor, Club clubByClubHome, Date date, String location, Set<Bet> bets,
			Set<Results> resultses, Set<Bookmaker> bookmakers) {
		this.clubByClubVisitor = clubByClubVisitor;
		this.clubByClubHome = clubByClubHome;
		this.date = date;
		this.location = location;
		this.bets = bets;
		this.resultses = resultses;
		this.bookmakers = bookmakers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "match_id", unique = true, nullable = false)
	public Integer getMatchId() {
		return this.matchId;
	}

	public void setMatchId(Integer matchId) {
		this.matchId = matchId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "club_visitor")
	public Club getClubByClubVisitor() {
		return this.clubByClubVisitor;
	}

	public void setClubByClubVisitor(Club clubByClubVisitor) {
		this.clubByClubVisitor = clubByClubVisitor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "club_home")
	public Club getClubByClubHome() {
		return this.clubByClubHome;
	}

	public void setClubByClubHome(Club clubByClubHome) {
		this.clubByClubHome = clubByClubHome;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "location", length = 45)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "match")
	public Set<Bet> getBets() {
		return this.bets;
	}

	public void setBets(Set<Bet> bets) {
		this.bets = bets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "match")
	public Set<Results> getResultses() {
		return this.resultses;
	}

	public void setResultses(Set<Results> resultses) {
		this.resultses = resultses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "match")
	public Set<Bookmaker> getBookmakers() {
		return this.bookmakers;
	}

	public void setBookmakers(Set<Bookmaker> bookmakers) {
		this.bookmakers = bookmakers;
	}

}
