package fr.formation.inti.entities;
// Generated 4 mai 2022, 11:33:36 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Past;
import javax.validation.constraints.Size;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "ligue1_gamble")
public class Person implements java.io.Serializable {

	private Integer personId;
	@NotEmpty(message = "Champ requis")
	private String firstName;
	@NotEmpty(message = "Champ requis")
	private String lastName;


	@Past
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date birthDate;
	@NotEmpty(message = "Champ requis")
	private String gender;
	@NotEmpty(message = "Champ requis")
	private String adress;
	@NotEmpty(message = "Champ requis")
	@Size(min = 5, max = 5, message = "Code postal à 5 chiffres")
	private String zipCode;
	@NotEmpty(message = "Champ requis")
	private String cityName;
	@NotEmpty(message = "Champ requis")
	@Size(min = 10, max = 10, message = "Numéro à 10 chiffres")
	private String telephone;
	private Set<User> users = new HashSet<User>(0);
	
	
	

	@Override
	public String toString() {
		return "Person [personId=" + personId + ", firstName=" + firstName + ", lastName=" + lastName + ", birthDate="
				+ birthDate + ", gender=" + gender + ", adress=" + adress + ", zipCode=" + zipCode + ", cityName="
				+ cityName + ", telephone=" + telephone + "]";
	}

	public Person() {
	}

	public Person(String firstName, String lastName, Date birthDate, String adress, String zipCode, String cityName,
			String telephone) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDate = birthDate;
		this.adress = adress;
		this.zipCode = zipCode;
		this.cityName = cityName;
		this.telephone = telephone;
	}

	public Person(String firstName, String lastName, Date birthDate, String gender, String adress, String zipCode,
			String cityName, String telephone, Set<User> users) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDate = birthDate;
		this.gender = gender;
		this.adress = adress;
		this.zipCode = zipCode;
		this.cityName = cityName;
		this.telephone = telephone;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	

	@Column(name = "person_id", unique = true, nullable = false)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth_date", nullable = false, length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "gender", length = 20)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "adress", nullable = false, length = 45)
	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	@Column(name = "zip_code", nullable = false, length = 5)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "city_name", nullable = false, length = 45)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "telephone", nullable = false, length = 10)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "person")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
